#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset
set -x

# Apply migrations
alembic upgrade head

# Run Uvicorn server using ASGI (create_app is an app factory)
uvicorn app:create_app --factory --proxy-headers --workers=2 --loop uvloop --http httptools --host 0.0.0.0 --port 8000
